export const questions = [
  "Everyone had a crush on a TV character when they were teenagers. Who was yours ?",
  "If you could get one superpower, what would it be ?",
  "Which female celebrity would you want to take away for a weekend ?",
  "Your Romantic ideas/expectation about Love!",
  "When was the most peaceful day you have had ?",
  "If you could meet one person, dead or alive, who would it be ?",
  "If you could bring back one famous person from the dead, who would it be ?",
  "Give your three best past moments that you can’t forget in our friendship ?",
  "Tell me about three funniest friends you know in your life ?",
  "If you can invisible, tell what first things u do ?",
  "If u got a Chance to ask me something about My Personal Life ?",
  "Have you ever fantasized about a friend’s girlfriend ?",
  "If you are alone in Island and you have chance to have only one partner with u. whom you choose, why ?",
  "Gift for me ",
  "My Name in your Phone ",
  "How do u Feel Wen u talk to me ? ",
  "My nature ",
  "My weakness ",
  "Words about me ",
  "Dedicate a song 4 Me.",
  "Color for me ",
  "If you had to describe our relationship in 5 words, what would they be ? ",
  "Your First Reaction on My First Look ",
  "Advise for me ",
  "Describe in one word, Friendship is ",
  "One thing that u Love the Most about Me ",
  "The thing u like most in My Face ",
  "What was your first impression about me ? ",
  "I am your _",
  "What’s the best advice you’ve given or been given ? ",
  "Where do you want to be in 50 years ? ",
  "If I was your slave for a day, what would you ask me to do for you ? ",
  "Do you believe in love ? Why or why not ? ",
  "If you give another chance to live ur life. What will you do ? ",
  "Which is the song you associate with me on imagine ? ",
  "Describe your soul mate… ",
  "Who is your secret crush ? ",
  "What will be your Reaction, when you will find out that I’m dead ?",
  "What is your deepest fear ? ",
  "Describe in one word, LIFE is ",
  "Did you ever have a crush on your teacher or someone much older when you were a kid ?",
  "Suggest a TV show for me to watch. ",
  "Suggest a website for me to go to. ",
  "What was your first impression about me ? ",
  "Who is your secret crush ? ",
];
